name: Build and push main image

on:
  push:
    tags:
      - '*'

jobs:
  push-store-image:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.ACCESS_TOKEN}}

      - name: 'Setup Variables'
        run: |
          GIT_TAG=${{ github.ref }}
          echo "GIT_TAG=${GIT_TAG#refs/tags/}" >> $GITHUB_ENV
          echo "IMAGE_NAME=ghcr.io/remvze/moodist" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
  
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: 'Build Inventory Image'
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME }}:${{ env.GIT_TAG }}
          platforms: linux/amd64,linux/arm64
